
module.exports = async (client, interaction, args) => {

    const user = interaction.options.getUser('user');

    var roasts = [
        "*Te mete en el horno.*",
        "Eres tan estúpido.",
        "Lo siento, no puedo oírte por lo molesto que eres..",
        "Tengo mejores cosas que hacer",
        "Eres tan tonto como Cleverbot",
        "Tu coeficiente intelectual es más bajo que la Fosa de las Marianas",
        "Eres tan molesto que hasta las moscas se alejan de tu hedor",
        "Vete, por favor",
        "Te miraría mal, pero ya lo has hecho",
        "Parece que tu cara se incendió y alguien trató de apagarla con un martillo",
        "Tu árbol genealógico debe ser un cactus porque todos son unos gilipollas",
        "Algún día llegarás lejos, y espero que te quedes allí",
        "Llamaron del zoológico. Se preguntan cómo saliste de tu jaula",
        "Esperaba una batalla de ingenio, pero pareces estar desarmado",
        "Eres la prueba de que la evolución puede ir al revés",
        "El cerebro no lo es todo, en tu caso, no es nada",
        "Lo siento, no lo entendí, no hablo idiota.",
        "¿Por qué es aceptable para ti ser un idiota, pero no para mí señalarlo?",
        "Todos surgimos de los monos, pero tú no lo hiciste lo suficiente",
        "Incluso los monos pueden ir al espacio, así que claramente te falta potencial",
        "El cerebro está por encima de los músculos, pero tú no tienes ni lo uno ni lo otro",
        "Pareces un mono, y hueles como uno también",
        "Incluso entre idiotas te faltan",
        "Fracasas incluso cuando no haces absolutamente nada",
        "Si hubiera una votación para 'menos probabilidades de éxito' ganarías el primer premio",
        "Estoy rodeado de idiotas... O, espera, sólo eres tú",
        "Quiero irme a casa. Bueno, en realidad sólo quiero alejarme del horrible aroma que tienes allí",
        "Cada vez que me tocas tengo que ir a casa y lavar toda mi ropa nueve veces sólo para recuperar un olor normal",
        "Si tuviera un dólar por cada cerebro que no tienes, tendría un dólar",
        "Te ayudaría a triunfar pero eres incapaz",
        "Tu pelo está construido como un gráfico, las fuerzas positivas y negativas se atraen pero la maquinilla y tu pelo se repelen",
        "¡Conozco un buen chiste! Tú",
        "Tienes dos partes del cerebro, la 'izquierda' y la 'derecha'. En el lado izquierdo, no hay nada derecho. En el lado derecho, no hay nada a la izquierda",
        "¿Tu culo está celoso de la cantidad de mierda que acaba de salir de tu boca?",
        "No entablo combate mental con los desarmados",
        "Dos errores no hacen un acierto, toma a tus padres como ejemplo",
        "Tu certificado de nacimiento es una carta de disculpa de la fábrica de condones",
        "Pareces razonable. Debe ser hora de aumentar mi medicación",
        "Debes haber nacido en una autopista porque es donde ocurren la mayoría de los accidentes",
        "Eres tan feo que cuando tu madre te dejó en el colegio la multaron por tirar basura",
        "Si la risa es la mejor medicina, tu cara debe estar curando al mundo",
        "Me gustaría ver las cosas desde tu punto de vista pero parece que no puedo meter la cabeza tan adentro de mi culo.",
        "La única forma de que eches un polvo es si te arrastras por el culo de una gallina y esperas",
        "¡Estoy celoso de toda la gente que no te ha conocido!",
        "Si tuviera una cara como la tuya, demandaría a mis padres",
        "Sólo hay un problema con tu cara. Puedo verlo",
        "¿No amas la naturaleza, a pesar de lo que te hizo?",
        "¿En qué idioma estás hablando? Porque suena a mierda",
        "La estupidez no es un crimen, así que eres libre de irte",
        "Entonces, ¿un pensamiento cruzó tu mente? Debe haber sido un viaje largo y solitario",
        "Tienes un coeficiente intelectual a temperatura ambiente - si la habitación está en la Antártida",
        "Si realmente quieres saber sobre errores, deberías preguntarle a tus padres",
        "Te preguntaría cuántos años tienes, pero sé que no sabes contar tan alto",
        "¿Quieres saber cómo consigo todos estos insultos? Uso algo llamado inteligencia",
        "Iba a mirarte mal, pero ya tienes una",
        "No sé cuál es tu problema, pero apuesto a que es difícil de pronunciar",
        "Los cerebros no lo son todo. En tu caso no son nada",
        "Como forastero, ¿qué piensas de la raza humana?",
        "Pareces una foto de antes",
        "¿Qué? Perdona. Intentaba imaginarte con personalidad",
        "Eres la razón por la que la piscina genética necesita un salvavidas",
        "Siempre podemos saber cuando estás mintiendo. Tus labios se mueven",
        "Puede que me encante ir de compras, pero no voy a comprar tu mierda",
        "El infierno está empapelado con todos tus selfies borrados",
        "Eres la prueba viviente de que al estiércol le pueden salir piernas y caminar",
        "¿Te das cuenta de que el maquillaje no va a arreglar tu estupidez?",
        "Llamarte idiota sería un insulto a toda la gente estúpida",
        "Tienes la cara perfecta para la radio",
        "Aww, es tan lindo cuando tratas de hablar de cosas que no entiendes.",
        "Si quisiera escuchar a un imbécil, me tiraría un pedo",
        "¿Cuál es la diferencia entre tú y un huevo? Los huevos se ponen",
        "Pareces una piedra aplastada en un montón de arena, enrollada en un canuto, y fumada a través de un inhalador para el asma",
        "Tus consejos son tan útiles como un refugio antiaéreo de papel maché",
        "¿Es triste que tu tema musical tenga una firma 0/0?",
        "Eres tan gordo que haces que la galaxia parezca estar en la escala molecular",
    ];

    client.embed({
        title: `😓・Roast`,
        desc: `${user}, ${roasts[Math.floor(Math.random() * roasts.length)]}`,
        type: 'editreply'
    }, interaction)
}

 